### ISSUE TITLE
Add the hero section

### ISSUE THREAD

**Issue by muchirijane** [muchirijane/next-product-site#10]
**Is your feature request related to a problem? Please describe.**
There is only the navbar on the website, you can add the hero section to be below it.

**Describe the solution you'd like**
Use material UI to create the component and add it to the home page (index.js).
Ensure to make the section responsive on desktop, laptop and mobile devices. 

### Desktop view
![hero-section desktop](https://user-images.githubusercontent.com/54930887/136713680-95020b95-a8b4-461d-9a23-6e26f591c597.png)

### mobile view
![mobile_hero-section](https://user-images.githubusercontent.com/54930887/136713763-6f377767-12b1-4167-aaf4-4a35977d8073.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Check out the theme js file in the src folder for the site palette.

**Comment by abhishek7997** [comment]
Please assign the issue to me. @muchirijane

**Comment by muchirijane** [comment]
Cool, let me do that.
