### ISSUE TITLE
Add the sponsor and product section

### ISSUE THREAD

**Issue by muchirijane** [muchirijane/next-product-site#23]
**Is your feature request related to a problem? Please describe.**
Add the product and the sponsor section on the customers page.

**Describe the solution you'd like**
The assets needed will be in the `website-assets` folder. The SVG for the page, images of the desktop and mobile view is also included. Ensure you make the sections responsive. 

<img width='400' src='https://user-images.githubusercontent.com/54930887/137026672-18b73294-a412-4a7a-9f16-3df6e054dcd7.png' alt='sponsor section'/> <img src='https://user-images.githubusercontent.com/54930887/137026779-e8df0c9e-a3a1-4fbd-a966-2996d415836b.png' alt='sponsor section' height='400'/>

**Describe alternatives you've considered**

**Additional context**
Use SVG for the logos instead of using png or jpeg images.

**Comment by chirayumit001** [comment]
Hey, can you assign me this !
