### ISSUE TITLE
Add how the product works section

### ISSUE THREAD

**Issue by muchirijane** [muchirijane/next-product-site#24]
**Is your feature request related to a problem? Please describe.**
Add the how the product works section and make it responsive. The assets are in the `Mackbook-resources-page.svg` in the `website-assets` folder.

**Describe the solution you'd like**
To make it easier for you, you can use Grid to make the section responsive to different devices. 
Below is the desktop and mobile view. 
<img width='400' src='https://user-images.githubusercontent.com/54930887/137028143-ceb9b889-6a1c-4b6f-a7b0-f4d7cf3fe457.png' alt='client section'/> <img src='https://user-images.githubusercontent.com/54930887/137028183-08d7454e-0916-46e0-a181-c49916c7fcff.png' alt='client section' height='400'/>

**Describe alternatives you've considered**
n/a

**Additional context**
The assets for the website are in the `website-assets` folder and before you push run `git pull origin develop` to get the updates before you push your branch. Also, remember to read the `contribution.md` file before cloning the project.

**Comment by alexjharrison** [comment]
@muchirijane Would you be able to extract out the images for each laptop and the two card images at the bottom?  Thanks.
